In [1]:
import pandas as pd

In [2]:
# Load data from Excel files
file1 = pd.read_excel("S_Data.xlsx")
file2 = pd.read_excel("T_Data.xlsx")

In [3]:
file1.head(9)

                                   S_Commodity Title  S_Commodity Code
0  Live Plant and Animal Material and Accessories...          10000000
1                                       Live animals          10100000
2                                          Livestock          10101500
3                                               Cats          10101501
4                                               Dogs          10101502
5                                               Mink          10101504
6                                               Rats          10101505
7                                             Horses          10101506
8                                              Sheep          10101507

In [4]:
file2

                                   T_Commodity Title  T_Commodity Code
0  Live Plant and Animal Material and Accessories...               NaN
1                                       Live animals               NaN
2                                          Livestock               NaN
3                                               Cats        10101501.0
4                                               Dogs        10101502.0
5                                               Mink        10101504.0
6                                 Cornell Misc Items        10101505.0
7                             Employee Reimbursement        10101506.0
8                                 Cornell Misc Items        10101507.0
9                                                ABC        99999999.0

In [5]:
file1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52958 entries, 0 to 52957
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S_Commodity Title  52958 non-null  object
 1   S_Commodity Code   52958 non-null  int64
dtypes: int64(1), object(1)
memory usage: 827.6+ KB

In [6]:
file2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   T_Commodity Title  10 non-null     object
 1   T_Commodity Code   7 non-null      float64
dtypes: float64(1), object(1)
memory usage: 292.0+ bytes

In [7]:
# Task 1: Inner join the two dataframes
joined_table = pd.merge(file2, file1, how="left", left_on="T_Commodity Title", right_on="S_Commodity Title")

In [8]:
# Task 2: Create observations column
def classify(row):
    if pd.isna(row['S_Commodity Title']):
        return "Commodity Title not in Standard Table"
    elif pd.isna(row['T_Commodity Code']):
        return "Unclassified"
    elif row['S_Commodity Code'] != row['T_Commodity Code']:
        return "Misclassified"
    else:
        return "Rightly Classified"

joined_table['Observations'] = joined_table.apply(classify, axis=1)

In [9]:
joined_table

,T_Commodity Title,T_Commodity Code,S_Commodity Title,S_Commodity Code,Observations
0,Live Plant and Animal Material and Accessories...,NaN,Live Plant and Animal Material and Accessories...,10000000.0,Unclassified
1,Live animals,NaN,Live animals,10100000.0,Unclassified
2,Livestock,NaN,Livestock,10101500.0,Unclassified
3,Cats,10101501.0,Cats,10101501.0,Rightly Classified
4,Dogs,10101502.0,Dogs,10101502.0,Rightly Classified
5,Mink,10101504.0,Mink,10101504.0,Rightly Classified
6,Cornell Misc Items,10101505.0,Cornell Misc Items,99000000.0,Misclassified
7,Cornell Misc Items,10101505.0,Cornell Misc Items,99200000.0,Misclassified
8,Employee Reimbursement,10101506.0,Employee Reimbursement,99100000.0,Misclassified
9,Cornell Misc Items,10101507.0,Cornell Misc Items,99000000.0,Misclassified
10,Cornell Misc Items,10101507.0,Cornell Misc Items,99200000.0,Misclassified
11,ABC,99999999.0,NaN,NaN,Commodity Title not in Standard Table

In [10]:
# Task 3: Create suggestions column
def suggest(row):
    if pd.isna(row['T_Commodity Code']):
        return row['S_Commodity Code']
    elif row['S_Commodity Code'] != row['T_Commodity Code']:
        return row['S_Commodity Code']
    else:
        return row['T_Commodity Code']

joined_table['Suggestions'] = joined_table.apply(suggest, axis=1)

In [11]:
joined_table

,T_Commodity Title,T_Commodity Code,S_Commodity Title,S_Commodity Code,Observations,Suggestions
0,Live Plant and Animal Material and Accessories...,NaN,Live Plant and Animal Material and Accessories...,10000000.0,Unclassified,10000000.0
1,Live animals,NaN,Live animals,10100000.0,Unclassified,10100000.0
2,Livestock,NaN,Livestock,10101500.0,Unclassified,10101500.0
3,Cats,10101501.0,Cats,10101501.0,Rightly Classified,10101501.0
4,Dogs,10101502.0,Dogs,10101502.0,Rightly Classified,10101502.0
5,Mink,10101504.0,Mink,10101504.0,Rightly Classified,10101504.0
6,Cornell Misc Items,10101505.0,Cornell Misc Items,99000000.0,Misclassified,99000000.0
7,Cornell Misc Items,10101505.0,Cornell Misc Items,99200000.0,Misclassified,99200000.0
8,Employee Reimbursement,10101506.0,Employee Reimbursement,99100000.0,Misclassified,99100000.0
9,Cornell Misc Items,10101507.0,Cornell Misc Items,99000000.0,Misclassified,99000000.0
10,Cornell Misc Items,10101507.0,Cornell Misc Items,99200000.0,Misclassified,99200000.0
11,ABC,99999999.0,NaN,NaN,Commodity Title not in Standard Table,NaN

In [12]:
# Filter out rows that are rightly classified
filtered_table = joined_table[joined_table['Observations'] != 'Rightly Classified']

# Display the filtered table
filtered_table

,T_Commodity Title,T_Commodity Code,S_Commodity Title,S_Commodity Code,Observations,Suggestions
0,Live Plant and Animal Material and Accessories...,NaN,Live Plant and Animal Material and Accessories...,10000000.0,Unclassified,10000000.0
1,Live animals,NaN,Live animals,10100000.0,Unclassified,10100000.0
2,Livestock,NaN,Livestock,10101500.0,Unclassified,10101500.0
6,Cornell Misc Items,10101505.0,Cornell Misc Items,99000000.0,Misclassified,99000000.0
7,Cornell Misc Items,10101505.0,Cornell Misc Items,99200000.0,Misclassified,99200000.0
8,Employee Reimbursement,10101506.0,Employee Reimbursement,99100000.0,Misclassified,99100000.0
9,Cornell Misc Items,10101507.0,Cornell Misc Items,99000000.0,Misclassified,99000000.0
10,Cornell Misc Items,10101507.0,Cornell Misc Items,99200000.0,Misclassified,99200000.0
11,ABC,99999999.0,NaN,NaN,Commodity Title not in Standard Table,NaN