In [1]:
import numpy as np
import pandas as pd

In [3]:
df_duplicates = pd.read_excel('Downloads/Duplicates.xlsx')
df_duplicates.head(3)

   CustomerID             Name            City
0         101   John Doe         New York
1         102   Jane Doe         Los Angeles
2         103   Bob Smith        Chicago

In [8]:
# Add a new column to flag duplicates
df_duplicates['IsDuplicate'] = df_duplicates.duplicated(subset=['Name', 'City'], keep=False)

In [9]:
df_duplicates.head(3)

    CustomerID             Name            City  IsDuplicate
3          104   Alice Johnson    Houston               True
18         119   Alice Johnson    Houston               True
13         114   Ava Miller       Columbus             False

In [10]:
df_duplicates = df_duplicates[df_duplicates['IsDuplicate'] == True]
df_duplicates

    CustomerID             Name            City  IsDuplicate
3          104   Alice Johnson    Houston               True
18         119   Alice Johnson    Houston               True
2          103   Bob Smith        Chicago               True
17         118   Bob Smith        Chicago               True
1          102   Jane Doe         Los Angeles           True
16         117   Jane Doe         Los Angeles           True
0          101   John Doe         New York              True
15         116   John Doe         New York              True

In [11]:
df_duplicates = df_duplicates.sort_values(by=['Name', 'City'])
df_duplicates

    CustomerID             Name            City  IsDuplicate
3          104   Alice Johnson    Houston               True
18         119   Alice Johnson    Houston               True
2          103   Bob Smith        Chicago               True
17         118   Bob Smith        Chicago               True
1          102   Jane Doe         Los Angeles           True
16         117   Jane Doe         Los Angeles           True
0          101   John Doe         New York              True
15         116   John Doe         New York              True