In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('Downloads/Excel_sales_w04_2.xlsx')

In [3]:
df.head(3)

,Row.ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer.Name,Segment,City,State,...,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Return
0,32298,CA-2012-124891,7/31/2012,7/31/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical,No
1,26341,IN-2013-77878,2013-05-02 00:00:00,2013-07-02 00:00:00,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical,Yes
2,25330,IN-2013-71249,2012-06-10 00:00:00,10/18/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25002 entries, 0 to 25001
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row.ID          25002 non-null  int64
 1   Order_ID        25002 non-null  object
 2   Order_Date      25002 non-null  object
 3   Ship_Date       25002 non-null  object
 4   Ship_Mode       25002 non-null  object
 5   Customer_ID     25002 non-null  object
 6   Customer.Name   25002 non-null  object
 7   Segment         24998 non-null  object
 8   City            25002 non-null  object
 9   State           25002 non-null  object
 10  Country         25002 non-null  object
 11  Postal.Code     4046 non-null   float64
 12  Market          25002 non-null  object
 13  Region          25002 non-null  object
 14  Product.ID      25002 non-null  object
 15  Category        25002 non-null  object
 16  Sub.Category    25002 non-null  object
 17  Product.Name    25002 non-null  object
 18  Sales           24946 non-null  float64
 19  Quantity        25002 non-null  int64
 20  Discount        25002 non-null  float64
 21  Profit          25002 non-null  float64
 22  Shipping_Cost   25002 non-null  float64
 23  Order_Priority  25002 non-null  object
 24  Return          25002 non-null  object
dtypes: float64(5), int64(2), object(18)
memory usage: 4.8+ MB

In [5]:
df['Order_ID'].fillna(method='ffill', inplace=True)

In [6]:
#df.info()

In [7]:
from dateutil import parser

# Function to convert Excel date serial numbers to datetime
def convert_excel_date(serial_number):
    if pd.notnull(serial_number):
        try:
            return pd.to_datetime('1900-01-01') + pd.to_timedelta(serial_number, 'D')
        except ValueError:
            return pd.NaT
    else:
        return pd.NaT

# Function to parse various date formats
def parse_date(date_str):
    try:
        return parser.parse(str(date_str), fuzzy=True)
    except parser.ParserError:
        return pd.NaT

# Assuming 'Order_Date' is the column with different date formats
df['Order_DateN'] = df['Order_Date'].apply(lambda x: convert_excel_date(x) if isinstance(x, (int, float)) else parse_date(x))



# Extracting date-related information
df['Date'] = pd.to_datetime(df['Order_DateN'], errors='coerce', format='%m/%d/%Y')
df['Year'] = df['Order_DateN'].dt.year

# Handle non-finite values in Quarter
df['Quarter'] = df['Order_DateN'].dt.quarter
df['Quarter'] = df['Quarter'].replace([np.inf, -np.inf, np.nan], 0).astype(int)

df['Quarter_Name'] = df['Order_DateN'].dt.to_period('Q').astype(str).str.replace(r'\d+Q', 'Q')
# Handle non-finite values in Month
df['Month'] = df['Order_DateN'].dt.month.replace([np.inf, -np.inf, np.nan], 0).astype(int)

df['Month_Name'] = df['Order_DateN'].dt.strftime('%B')
df['Month_Name_Short'] = df['Order_DateN'].dt.strftime('%b')  # Short month names
df['Week_Number'] = df['Order_DateN'].dt.isocalendar().week
# Handle non-finite values in Weekday
df['Weekday'] = (df['Order_DateN'].dt.weekday + 1).replace([np.inf, -np.inf, np.nan], 0).astype(int)  # Adding 1 to make Monday = 1, Sunday = 7

df['Weekday_Name'] = df['Order_DateN'].dt.strftime('%A')
df['Weekday_Name_Short'] = df['Order_DateN'].dt.strftime('%a')  # Short weekday names

# Displaying the resulting table
df_dates_by_manish = df[['Order_Date','Order_DateN', 'Date', 'Year', 'Quarter', 'Quarter_Name', 'Month', 'Month_Name', 'Month_Name_Short', 'Week_Number', 'Weekday', 'Weekday_Name', 'Weekday_Name_Short']].head(50)
df_dates_by_manish

,Order_Date,Order_DateN,Date,Year,Quarter,Quarter_Name,Month,Month_Name,Month_Name_Short,Week_Number,Weekday,Weekday_Name,Weekday_Name_Short
0,7/31/2012,2012-07-31,2012-07-31,2012,3,2012Q3,7,July,Jul,31,2,Tuesday,Tue
1,2013-05-02 00:00:00,2013-05-02,2013-05-02,2013,2,2013Q2,5,May,May,18,4,Thursday,Thu
2,2012-06-10 00:00:00,2012-06-10,2012-06-10,2012,2,2012Q2,6,June,Jun,23,7,Sunday,Sun
3,2005-01-28 00:00:00,2005-01-28,2005-01-28,2005,1,2005Q1,1,January,Jan,4,5,Friday,Fri
4,2013-05-11 00:00:00,2013-05-11,2013-05-11,2013,2,2013Q2,5,May,May,19,6,Saturday,Sat
5,2013-06-28 00:00:00,2013-06-28,2013-06-28,2013,2,2013Q2,6,June,Jun,26,5,Friday,Fri
6,2011-07-11 00:00:00,2011-07-11,2011-07-11,2011,3,2011Q3,7,July,Jul,28,1,Monday,Mon
7,04/14/2012,2012-04-14,2012-04-14,2012,2,2012Q2,4,April,Apr,15,6,Saturday,Sat
8,10/14/2014,2014-10-14,2014-10-14,2014,4,2014Q4,10,October,Oct,42,2,Tuesday,Tue
9,2012-01-28 00:00:00,2012-01-28,2012-01-28,2012,1,2012Q1,1,January,Jan,4,6,Saturday,Sat
10,2011-05-04 00:00:00,2011-05-04,2011-05-04,2011,2,2011Q2,5,May,May,18,3,Wednesday,Wed
11,4/19/2012,2012-04-19,2012-04-19,2012,2,2012Q2,4,April,Apr,16,4,Thursday,Thu
12,27 December 2011,2011-12-27,2011-12-27,2011,4,2011Q4,12,December,Dec,52,2,Tuesday,Tue
13,11/13/2012,2012-11-13,2012-11-13,2012,4,2012Q4,11,November,Nov,46,2,Tuesday,Tue
14,2013-06-06 00:00:00,2013-06-06,2013-06-06,2013,2,2013Q2,6,June,Jun,23,4,Thursday,Thu
15,7/31/2014,2014-07-31,2014-07-31,2014,3,2014Q3,7,July,Jul,31,4,Thursday,Thu
16,2014-03-11 00:00:00,2014-03-11,2014-03-11,2014,1,2014Q1,3,March,Mar,11,2,Tuesday,Tue
17,41860,2014-08-11,2014-08-11,2014,3,2014Q3,8,August,Aug,33,1,Monday,Mon
18,1/31/2014,2014-01-31,2014-01-31,2014,1,2014Q1,1,January,Jan,5,5,Friday,Fri
19,2014-05-12 00:00:00,2014-05-12,2014-05-12,2014,2,2014Q2,5,May,May,20,1,Monday,Mon
20,2012-08-08 00:00:00,2012-08-08,2012-08-08,2012,3,2012Q3,8,August,Aug,32,3,Wednesday,Wed
21,10/29/2011,2011-10-29,2011-10-29,2011,4,2011Q4,10,October,Oct,43,6,Saturday,Sat
22,40579,2011-02-07,2011-02-07,2011,1,2011Q1,2,February,Feb,6,1,Monday,Mon
23,2/27/2013,2013-02-27,2013-02-27,2013,1,2013Q1,2,February,Feb,9,3,Wednesday,Wed
24,31 Jul 2014,2014-07-31,2014-07-31,2014,3,2014Q3,7,July,Jul,31,4,Thursday,Thu
25,2014-05-09 00:00:00,2014-05-09,2014-05-09,2014,2,2014Q2,5,May,May,19,5,Friday,Fri
26,12/17/2011,2011-12-17,2011-12-17,2011,4,2011Q4,12,December,Dec,50,6,Saturday,Sat
27,3/14/2011,2011-03-14,2011-03-14,2011,1,2011Q1,3,March,Mar,11,1,Monday,Mon
28,2013-11-03 00:00:00,2013-11-03,2013-11-03,2013,4,2013Q4,11,November,Nov,44,7,Sunday,Sun
29,2/25/2012,2012-02-25,2012-02-25,2012,1,2012Q1,2,February,Feb,8,6,Saturday,Sat
30,2011-12-28 00:00:00,2011-12-28,2011-12-28,2011,4,2011Q4,12,December,Dec,52,3,Wednesday,Wed
31,15 Sep 2016,2016-09-15,2016-09-15,2016,3,2016Q3,9,September,Sep,37,4,Thursday,Thu
32,10/15/2012,2012-10-15,2012-10-15,2012,4,2012Q4,10,October,Oct,42,1,Monday,Mon
33,2011-03-11 00:00:00,2011-03-11,2011-03-11,2011,1,2011Q1,3,March,Mar,10,5,Friday,Fri
34,2011-12-12 00:00:00,2011-12-12,2011-12-12,2011,4,2011Q4,12,December,Dec,50,1,Monday,Mon
35,9/14/2011,2011-09-14,2011-09-14,2011,3,2011Q3,9,September,Sep,37,3,Wednesday,Wed
36,15 September 2012,2012-09-15,2012-09-15,2012,3,2012Q3,9,September,Sep,37,6,Saturday,Sat
37,2014-05-11 00:00:00,2014-05-11,2014-05-11,2014,2,2014Q2,5,May,May,19,7,Sunday,Sun
38,1/14/2014,2014-01-14,2014-01-14,2014,1,2014Q1,1,January,Jan,3,2,Tuesday,Tue
39,2011-10-01 00:00:00,2011-10-01,2011-10-01,2011,4,2011Q4,10,October,Oct,39,6,Saturday,Sat
40,8/22/2013,2013-08-22,2013-08-22,2013,3,2013Q3,8,August,Aug,34,4,Thursday,Thu
41,2014-11-11 00:00:00,2014-11-11,2014-11-11,2014,4,2014Q4,11,November,Nov,46,2,Tuesday,Tue
42,9/26/2014,2014-09-26,2014-09-26,2014,3,2014Q3,9,September,Sep,39,5,Friday,Fri
43,12/13/2012,2012-12-13,2012-12-13,2012,4,2012Q4,12,December,Dec,50,4,Thursday,Thu
44,9/23/2011,2011-09-23,2011-09-23,2011,3,2011Q3,9,September,Sep,38,5,Friday,Fri
45,9/23/2011,2011-09-23,2011-09-23,2011,3,2011Q3,9,September,Sep,38,5,Friday,Fri
46,2013-08-03 00:00:00,2013-08-03,2013-08-03,2013,3,2013Q3,8,August,Aug,31,6,Saturday,Sat
47,8/28/2014,2014-08-28,2014-08-28,2014,3,2014Q3,8,August,Aug,35,4,Thursday,Thu
48,2014-01-05 00:00:00,2014-01-05,2014-01-05,2014,1,2014Q1,1,January,Jan,1,7,Sunday,Sun
49,12/18/2014,2014-12-18,2014-12-18,2014,4,2014Q4,12,December,Dec,51,4,Thursday,Thu

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25002 entries, 0 to 25001
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row.ID              25002 non-null  int64
 1   Order_ID            25002 non-null  object
 2   Order_Date          25002 non-null  object
 3   Ship_Date           25002 non-null  object
 4   Ship_Mode           25002 non-null  object
 5   Customer_ID         25002 non-null  object
 6   Customer.Name       25002 non-null  object
 7   Segment             24998 non-null  object
 8   City                25002 non-null  object
 9   State               25002 non-null  object
 10  Country             25002 non-null  object
 11  Postal.Code         4046 non-null   float64
 12  Market              25002 non-null  object
 13  Region              25002 non-null  object
 14  Product.ID          25002 non-null  object
 15  Category            25002 non-null  object
 16  Sub.Category        25002 non-null  object
 17  Product.Name        25002 non-null  object
 18  Sales               24946 non-null  float64
 19  Quantity            25002 non-null  int64
 20  Discount            25002 non-null  float64
 21  Profit              25002 non-null  float64
 22  Shipping_Cost       25002 non-null  float64
 23  Order_Priority      25002 non-null  object
 24  Return              25002 non-null  object
 25  Order_DateN         25002 non-null  datetime64[ns]
 26  Date                25002 non-null  datetime64[ns]
 27  Year                25002 non-null  int32
 28  Quarter             25002 non-null  int32
 29  Quarter_Name        25002 non-null  object
 30  Month               25002 non-null  int32
 31  Month_Name          25002 non-null  object
 32  Month_Name_Short    25002 non-null  object
 33  Week_Number         25002 non-null  UInt32
 34  Weekday             25002 non-null  int32
 35  Weekday_Name        25002 non-null  object
 36  Weekday_Name_Short  25002 non-null  object
dtypes: UInt32(1), datetime64[ns](2), float64(5), int32(4), int64(2), object(23)
memory usage: 6.6+ MB

In [9]:
from IPython.display import FileLink

# Assuming the DataFrame is named df_dates_by_manish
df_dates_by_manish.to_excel('df_dates_by_manish.xlsx', index=False)

# Displaying a download link
FileLink(r'df_dates_by_manish.xlsx')

C:\Users\pawan\df_dates_by_manish.xlsx