In [1]:
import numpy as np
import pandas as pd

In [2]:
# Function to split quantity and unit from weight string
def split_weight(weight_str):
    quantity, unit = weight_str.split(' ')
    return float(quantity), unit

In [10]:
df_data = pd.read_excel('Conversion_data.xlsx')
df_data.head(3)

   ProductID    Name   Weight
0        401   Apple   0.2 kg
1        402  Banana  0.5 lbs
2        403  Orange    150 g

In [4]:
df_unit_conversion = pd.read_excel('Unit_Conversion.xlsx')
df_unit_conversion

  Base_Unit   To  Conversion Factor
0        kg   kg            1.00000
1        kg    g         1000.00000
2        kg  lbs            2.20462
3        kg   oz           35.27400

In [5]:
# Apply split_weight function to df_data table
df_data[['Quantity', 'Unit']] = df_data['Weight'].apply(lambda x: pd.Series(split_weight(x)))
df_data.head(3)

   ProductID    Name   Weight  Quantity Unit
0        401   Apple   0.2 kg       0.2   kg
1        402  Banana  0.5 lbs       0.5  lbs
2        403  Orange    150 g     150.0    g

In [6]:
# Merge df_data with unit_conversion table
merged_table = pd.merge(df_data, df_unit_conversion, left_on='Unit', right_on='To', how='left')
merged_table

,ProductID,Name,Weight,Quantity,Unit,Base_Unit,To,Conversion Factor
0,401,Apple,0.2 kg,0.20,kg,kg,kg,1.00000
1,402,Banana,0.5 lbs,0.50,lbs,kg,lbs,2.20462
2,403,Orange,150 g,150.00,g,kg,g,1000.00000
3,404,Pineapple,1.2 kg,1.20,kg,kg,kg,1.00000
4,405,Watermelon,2.5 kg,2.50,kg,kg,kg,1.00000
5,406,Strawberry,8 oz,8.00,oz,kg,oz,35.27400
6,407,Mango,300 g,300.00,g,kg,g,1000.00000
7,408,Pear,0.4 kg,0.40,kg,kg,kg,1.00000
8,409,Grapes,1.5 lbs,1.50,lbs,kg,lbs,2.20462
9,410,Kiwi,200 g,200.00,g,kg,g,1000.00000
10,411,Peach,0.3 kg,0.30,kg,kg,kg,1.00000
11,412,Plum,12 oz,12.00,oz,kg,oz,35.27400
12,413,Blueberry,180 g,180.00,g,kg,g,1000.00000
13,414,Raspberry,0.6 kg,0.60,kg,kg,kg,1.00000
14,415,Papaya,3.5 lbs,3.50,lbs,kg,lbs,2.20462
15,416,Avocado,400 g,400.00,g,kg,g,1000.00000
16,417,Lemon,0.25 kg,0.25,kg,kg,kg,1.00000
17,418,Lime,6 oz,6.00,oz,kg,oz,35.27400
18,419,Cherry,250 g,250.00,g,kg,g,1000.00000
19,420,Guava,0.7 kg,0.70,kg,kg,kg,1.00000

In [8]:
# Calculate weights in kilograms
merged_table['Weight_in_kg'] = merged_table['Quantity'] / merged_table['Conversion Factor']

In [9]:
merged_table[['ProductID', 'Name', 'Weight', 'Weight_in_kg']]

    ProductID        Name   Weight  Weight_in_kg
0         401       Apple   0.2 kg      0.200000
1         402      Banana  0.5 lbs      0.226796
2         403      Orange    150 g      0.150000
3         404   Pineapple   1.2 kg      1.200000
4         405  Watermelon   2.5 kg      2.500000
5         406  Strawberry     8 oz      0.226796
6         407       Mango    300 g      0.300000
7         408        Pear   0.4 kg      0.400000
8         409      Grapes  1.5 lbs      0.680389
9         410        Kiwi    200 g      0.200000
10        411       Peach   0.3 kg      0.300000
11        412        Plum    12 oz      0.340194
12        413   Blueberry    180 g      0.180000
13        414   Raspberry   0.6 kg      0.600000
14        415      Papaya  3.5 lbs      1.587575
15        416     Avocado    400 g      0.400000
16        417       Lemon  0.25 kg      0.250000
17        418        Lime     6 oz      0.170097
18        419      Cherry    250 g      0.250000
19        420       Guava   0.7 kg      0.700000